use MiniAirline
go

--- DIRTY READS
BEGIN TRANSACTION
UPDATE Aircraft 
SET Manufacturer = 'Bombardier'
WHERE AircraftID = 1
WAITFOR DELAY '00:00:10'
ROLLBACK TRANSACTION

--- NON-REPEATABLE READS
INSERT INTO Aircraft(Manufacturer, Capacity) VALUES ('Airbus', 630)
BEGIN TRANSACTION
WAITFOR DELAY '00:00:10'
UPDATE Aircraft 
SET Capacity = 300
WHERE AircraftID = (SELECT IDENT_CURRENT('Aircraft'))
COMMIT TRANSACTION


--- PHANTOM READS
BEGIN TRANSACTION
WAITFOR DELAY '00:00:10'
INSERT INTO Pilot(Name, Age) VALUES ('Ema Anitei', 22)
COMMIT TRANSACTION

--- DEADLOCK
BEGIN TRANSACTION
UPDATE Pilot SET Name='Lezi Frunza' WHERE PilotID=3
WAITFOR DELAY '00:00:10'
UPDATE Pilot SET Name='Sabina Atodiresei' WHERE PilotID=2
COMMIT TRAN


SET DEADLOCK_PRIORITY LOW
BEGIN TRANSACTION
UPDATE Pilot SET Name='Lezi Frunza' WHERE PilotID=3
WAITFOR DELAY '00:00:10'
UPDATE Pilot SET Name='Sabina Atodiresei' WHERE PilotID=2
COMMIT TRAN



SELECT * FROM Aircraft
SELECT * FROM Flight
SELECT * FROM Pilot