--- DIRTY READS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Aircraft
WAITFOR DELAY '00:00:15'
SELECT * FROM Aircraft
COMMIT TRAN

-- solution
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Aircraft
WAITFOR DELAY '00:00:15'
SELECT * FROM Aircraft
COMMIT TRAN


--- NON-REPEATABLE READS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Aircraft
WAITFOR DELAY '00:00:15'
SELECT * FROM Aircraft
COMMIT TRAN

-- solution
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Aircraft
WAITFOR DELAY '00:00:15'
SELECT * FROM Aircraft
COMMIT TRAN


--- PHANTOM READS
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Pilot
WAITFOR DELAY '00:00:15'
SELECT * FROM Pilot
COMMIT TRAN

-- solution
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Aircraft
WAITFOR DELAY '00:00:15'
SELECT * FROM Aircraft
COMMIT TRAN

--- DEADLOCK
BEGIN TRANSACTION
UPDATE Pilot SET Name='Dan Cimpan' WHERE PilotID=2
WAITFOR DELAY '00:00:10'
UPDATE Pilot SET Name='Mara Chit' WHERE PilotID=3
COMMIT TRAN

-- solution
--- decide an order and stick to it
BEGIN TRANSACTION
UPDATE Pilot SET Name='Dan Cimpan' WHERE PilotID=3
WAITFOR DELAY '00:00:10'
UPDATE Pilot SET Name='Mara Chit' WHERE PilotID=2
COMMIT TRAN

-- OOOOR deadlock priority
SET DEADLOCK_PRIORITY HIGH
BEGIN TRANSACTION
UPDATE Pilot SET Name='Dan Cimpan' WHERE PilotID=3
WAITFOR DELAY '00:00:10'
UPDATE Pilot SET Name='Mara Chit' WHERE PilotID=2
COMMIT TRAN